### ISSUE TITLE
1.2 extract defect area with ORB

### ISSUE THREAD

**Issue by brique-co-kr** [brique-co-kr/adc#2]
## ToDo List
- [x] check the possibility of ORB for semi-conductor images (18/05/25 > 18/05/28)
- [ ] check whether the key points located on the interesting area 
- [ ] check the optimal number of key points
- [ ] extract defect area

**Comment by brique-co-kr** [comment]
comment here

**Comment by brique-co-kr** [comment]
comment here

**Comment by brique-co-kr** [comment]
![image](https://user-images.githubusercontent.com/39188237/40224790-2f01910a-5ac2-11e8-870e-1eb76fc41508.png)

**Comment by brique-co-kr** [comment]
![image](https://user-images.githubusercontent.com/39188237/40457719-e908603c-5f32-11e8-849a-7a3c98a34734.png)
